# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:37:48+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class BidderLocationItem(BaseModel):
    bidProtocol: Optional[str] = Field(
        None,
        description='The protocol that the bidder endpoint is using. OpenRTB protocols with prefix PROTOCOL_OPENRTB_PROTOBUF use proto buffer, otherwise use JSON.  Allowed values:  \n- PROTOCOL_ADX \n- PROTOCOL_OPENRTB_2_2 \n- PROTOCOL_OPENRTB_2_3 \n- PROTOCOL_OPENRTB_2_4 \n- PROTOCOL_OPENRTB_2_5 \n- PROTOCOL_OPENRTB_PROTOBUF_2_3 \n- PROTOCOL_OPENRTB_PROTOBUF_2_4 \n- PROTOCOL_OPENRTB_PROTOBUF_2_5',
    )
    maximumQps: Optional[int] = Field(
        None, description='The maximum queries per second the Ad Exchange will send.'
    )
    region: Optional[str] = Field(
        None,
        description='The geographical region the Ad Exchange should send requests from. Only used by some quota systems, but always setting the value is recommended. Allowed values:  \n- ASIA \n- EUROPE \n- US_EAST \n- US_WEST',
    )
    url: Optional[str] = Field(
        None, description='The URL to which the Ad Exchange will send bid requests.'
    )


class Account(BaseModel):
    applyPretargetingToNonGuaranteedDeals: Optional[bool] = Field(
        None,
        description='When this is false, bid requests that include a deal ID for a private auction or preferred deal are always sent to your bidder. When true, all active pretargeting configs will be applied to private auctions and preferred deals. Programmatic Guaranteed deals (when enabled) are always sent to your bidder.',
    )
    bidderLocation: Optional[List[BidderLocationItem]] = Field(
        None, description='Your bidder locations that have distinct URLs.'
    )
    cookieMatchingNid: Optional[str] = Field(
        None,
        description='The nid parameter value used in cookie match requests. Please contact your technical account manager if you need to change this.',
    )
    cookieMatchingUrl: Optional[str] = Field(
        None, description='The base URL used in cookie match requests.'
    )
    id: Optional[int] = Field(None, description='Account id.')
    kind: Optional[str] = Field('adexchangebuyer#account', description='Resource type.')
    maximumActiveCreatives: Optional[int] = Field(
        None,
        description='The maximum number of active creatives that an account can have, where a creative is active if it was inserted or bid with in the last 30 days. Please contact your technical account manager if you need to change this.',
    )
    maximumTotalQps: Optional[int] = Field(
        None,
        description='The sum of all bidderLocation.maximumQps values cannot exceed this. Please contact your technical account manager if you need to change this.',
    )
    numberActiveCreatives: Optional[int] = Field(
        None,
        description='The number of creatives that this account inserted or bid with in the last 30 days.',
    )


class AccountsList(BaseModel):
    items: Optional[List[Account]] = Field(None, description='A list of accounts.')
    kind: Optional[str] = Field(
        'adexchangebuyer#accountsList', description='Resource type.'
    )


class BillingInfo(BaseModel):
    accountId: Optional[int] = Field(None, description='Account id.')
    accountName: Optional[str] = Field(None, description='Account name.')
    billingId: Optional[List[str]] = Field(
        None,
        description='A list of adgroup IDs associated with this particular account. These IDs may show up as part of a realtime bidding BidRequest, which indicates a bid request for this account.',
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#billingInfo', description='Resource type.'
    )


class BillingInfoList(BaseModel):
    items: Optional[List[BillingInfo]] = Field(
        None, description='A list of billing info relevant for your account.'
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#billingInfoList', description='Resource type.'
    )


class Budget(BaseModel):
    accountId: Optional[str] = Field(
        None,
        description='The id of the account. This is required for get and update requests.',
    )
    billingId: Optional[str] = Field(
        None,
        description='The billing id to determine which adgroup to provide budget information for. This is required for get and update requests.',
    )
    budgetAmount: Optional[str] = Field(
        None,
        description='The daily budget amount in unit amount of the account currency to apply for the billingId provided. This is required for update requests.',
    )
    currencyCode: Optional[str] = Field(
        None,
        description='The currency code for the buyer. This cannot be altered here.',
    )
    id: Optional[str] = Field(
        None, description='The unique id that describes this item.'
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#budget',
        description='The kind of the resource, i.e. "adexchangebuyer#budget".',
    )


class Buyer(BaseModel):
    accountId: Optional[str] = Field(None, description='Adx account id of the buyer.')


class ContactInformation(BaseModel):
    email: Optional[str] = Field(None, description='Email address of the contact.')
    name: Optional[str] = Field(None, description='The name of the contact.')


class AdTechnologyProviders(BaseModel):
    detectedProviderIds: Optional[List[str]] = Field(
        None,
        description='The detected ad technology provider IDs for this creative. See https://storage.googleapis.com/adx-rtb-dictionaries/providers.csv for mapping of provider ID to provided name, a privacy policy URL, and a list of domains which can be attributed to the provider. If this creative contains provider IDs that are outside of those listed in the `BidRequest.adslot.consented_providers_settings.consented_providers` field on the  Authorized Buyers Real-Time Bidding protocol or the `BidRequest.user.ext.consented_providers_settings.consented_providers` field on the OpenRTB protocol, a bid submitted for a European Economic Area (EEA) user with this creative is not compliant with the GDPR policies as mentioned in the "Third-party Ad Technology Vendors" section of Authorized Buyers Program Guidelines.',
    )
    hasUnidentifiedProvider: Optional[bool] = Field(
        None,
        description='Whether the creative contains an unidentified ad technology provider. If true, a bid submitted for a European Economic Area (EEA) user with this creative is not compliant with the GDPR policies as mentioned in the "Third-party Ad Technology Vendors" section of Authorized Buyers Program Guidelines.',
    )


class Context(BaseModel):
    auctionType: Optional[List[str]] = Field(
        None,
        description='Only set when contextType=AUCTION_TYPE. Represents the auction types this correction applies to.',
    )
    contextType: Optional[str] = Field(
        None,
        description='The type of context (e.g., location, platform, auction type, SSL-ness).',
    )
    geoCriteriaId: Optional[List[int]] = Field(
        None,
        description='Only set when contextType=LOCATION. Represents the geo criterias this correction applies to.',
    )
    platform: Optional[List[str]] = Field(
        None,
        description='Only set when contextType=PLATFORM. Represents the platforms this correction applies to.',
    )


class Correction(BaseModel):
    contexts: Optional[List[Context]] = Field(
        None,
        description='All known serving contexts containing serving status information.',
    )
    details: Optional[List[str]] = Field(
        None, description='Additional details about the correction.'
    )
    reason: Optional[str] = Field(
        None, description='The type of correction that was applied to the creative.'
    )


class Reason(BaseModel):
    filteringCount: Optional[str] = Field(
        None,
        description='The number of times the creative was filtered for the status. The count is aggregated across all publishers on the exchange.',
    )
    filteringStatus: Optional[int] = Field(
        None,
        description='The filtering status code as defined in  creative-status-codes.txt.',
    )


class FilteringReasons(BaseModel):
    date: Optional[str] = Field(
        None,
        description='The date in ISO 8601 format for the data. The data is collected from 00:00:00 to 23:59:59 in PST.',
    )
    reasons: Optional[List[Reason]] = Field(None, description='The filtering reasons.')


class AppIcon(BaseModel):
    height: Optional[int] = None
    url: Optional[str] = None
    width: Optional[int] = None


class Image(BaseModel):
    height: Optional[int] = None
    url: Optional[str] = None
    width: Optional[int] = None


class Logo(BaseModel):
    height: Optional[int] = None
    url: Optional[str] = None
    width: Optional[int] = None


class NativeAd(BaseModel):
    advertiser: Optional[str] = None
    appIcon: Optional[AppIcon] = Field(
        None, description='The app icon, for app download ads.'
    )
    body: Optional[str] = Field(None, description='A long description of the ad.')
    callToAction: Optional[str] = Field(
        None, description='A label for the button that the user is supposed to click.'
    )
    clickLinkUrl: Optional[str] = Field(
        None,
        description='The URL that the browser/SDK will load when the user clicks the ad.',
    )
    clickTrackingUrl: Optional[str] = Field(
        None, description='The URL to use for click tracking.'
    )
    headline: Optional[str] = Field(None, description='A short title for the ad.')
    image: Optional[Image] = Field(None, description='A large image.')
    impressionTrackingUrl: Optional[List[str]] = Field(
        None, description='The URLs are called when the impression is rendered.'
    )
    logo: Optional[Logo] = Field(
        None, description='A smaller image, for the advertiser logo.'
    )
    price: Optional[str] = Field(
        None, description='The price of the promoted app including the currency info.'
    )
    starRating: Optional[float] = Field(
        None, description='The app rating in the app store. Must be in the range [0-5].'
    )
    videoURL: Optional[str] = Field(
        None,
        description='The URL of the XML VAST for a native ad. Note this is a separate field from resource.video_url.',
    )


class Context1(BaseModel):
    auctionType: Optional[List[str]] = Field(
        None,
        description='Only set when contextType=AUCTION_TYPE. Represents the auction types this restriction applies to.',
    )
    contextType: Optional[str] = Field(
        None,
        description='The type of context (e.g., location, platform, auction type, SSL-ness).',
    )
    geoCriteriaId: Optional[List[int]] = Field(
        None,
        description='Only set when contextType=LOCATION. Represents the geo criterias this restriction applies to. Impressions are considered to match a context if either the user location or publisher location matches a given geoCriteriaId.',
    )
    platform: Optional[List[str]] = Field(
        None,
        description='Only set when contextType=PLATFORM. Represents the platforms this restriction applies to.',
    )


class DisapprovalReason(BaseModel):
    details: Optional[List[str]] = Field(
        None, description='Additional details about the reason for disapproval.'
    )
    reason: Optional[str] = Field(
        None, description='The categorized reason for disapproval.'
    )


class ServingRestriction(BaseModel):
    contexts: Optional[List[Context1]] = Field(
        None, description='All known contexts/restrictions.'
    )
    disapprovalReasons: Optional[List[DisapprovalReason]] = Field(
        None,
        description='The reasons for disapproval within this restriction, if any. Note that not all disapproval reasons may be categorized, so it is possible for the creative to have a status of DISAPPROVED or CONDITIONALLY_APPROVED with an empty list for disapproval_reasons. In this case, please reach out to your TAM to help debug the issue.',
    )
    reason: Optional[str] = Field(
        None,
        description='Why the creative is ineligible to serve in this context (e.g., it has been explicitly disapproved or is pending review).',
    )


class Creative(BaseModel):
    HTMLSnippet: Optional[str] = Field(
        None,
        description='The HTML snippet that displays the ad when inserted in the web page. If set, videoURL, videoVastXML, and nativeAd should not be set.',
    )
    accountId: Optional[int] = Field(None, description='Account id.')
    adChoicesDestinationUrl: Optional[str] = Field(
        None,
        description='The link to the Ad Preferences page. This is only supported for native ads.',
    )
    adTechnologyProviders: Optional[AdTechnologyProviders] = None
    advertiserId: Optional[List[str]] = Field(
        None,
        description='Detected advertiser id, if any. Read-only. This field should not be set in requests.',
    )
    advertiserName: Optional[str] = Field(
        None,
        description='The name of the company being advertised in the creative. A list of advertisers is provided in the advertisers.txt file.',
    )
    agencyId: Optional[str] = Field(
        None, description='The agency id for this creative.'
    )
    apiUploadTimestamp: Optional[datetime] = Field(
        None,
        description='The last upload timestamp of this creative if it was uploaded via API. Read-only. The value of this field is generated, and will be ignored for uploads. (formatted RFC 3339 timestamp).',
    )
    attribute: Optional[List[int]] = Field(
        None,
        description='List of buyer selectable attributes for the ads that may be shown from this snippet. Each attribute is represented by an integer as defined in  buyer-declarable-creative-attributes.txt.',
    )
    buyerCreativeId: Optional[str] = Field(
        None, description='A buyer-specific id identifying the creative in this ad.'
    )
    clickThroughUrl: Optional[List[str]] = Field(
        None, description='The set of destination urls for the snippet.'
    )
    corrections: Optional[List[Correction]] = Field(
        None,
        description='Shows any corrections that were applied to this creative. Read-only. This field should not be set in requests.',
    )
    creativeStatusIdentityType: Optional[str] = Field(
        None,
        description='Creative status identity type that the creative item applies to. Ad Exchange real-time bidding is migrating to the sizeless creative verification. Originally, Ad Exchange assigned creative verification status to a unique combination of a buyer creative ID and creative dimensions. Post-migration, a single verification status will be assigned at the buyer creative ID level. This field allows to distinguish whether a given creative status applies to a unique combination of a buyer creative ID and creative dimensions, or to a buyer creative ID as a whole.',
    )
    dealsStatus: Optional[str] = Field(
        None,
        description='Top-level deals status. Read-only. This field should not be set in requests. If disapproved, an entry for auctionType=DIRECT_DEALS (or ALL) in servingRestrictions will also exist. Note that this may be nuanced with other contextual restrictions, in which case it may be preferable to read from servingRestrictions directly.',
    )
    detectedDomains: Optional[List[str]] = Field(
        None,
        description='Detected domains for this creative. Read-only. This field should not be set in requests.',
    )
    filteringReasons: Optional[FilteringReasons] = Field(
        None,
        description='The filtering reasons for the creative. Read-only. This field should not be set in requests.',
    )
    height: Optional[int] = Field(None, description='Ad height.')
    impressionTrackingUrl: Optional[List[str]] = Field(
        None, description='The set of urls to be called to record an impression.'
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#creative', description='Resource type.'
    )
    languages: Optional[List[str]] = Field(
        None,
        description='Detected languages for this creative. Read-only. This field should not be set in requests.',
    )
    nativeAd: Optional[NativeAd] = Field(
        None,
        description='If nativeAd is set, HTMLSnippet, videoVastXML, and the videoURL outside of nativeAd should not be set. (The videoURL inside nativeAd can be set.)',
    )
    openAuctionStatus: Optional[str] = Field(
        None,
        description='Top-level open auction status. Read-only. This field should not be set in requests. If disapproved, an entry for auctionType=OPEN_AUCTION (or ALL) in servingRestrictions will also exist. Note that this may be nuanced with other contextual restrictions, in which case it may be preferable to read from ServingRestrictions directly.',
    )
    productCategories: Optional[List[int]] = Field(
        None,
        description='Detected product categories, if any. Each category is represented by an integer as defined in  ad-product-categories.txt. Read-only. This field should not be set in requests.',
    )
    restrictedCategories: Optional[List[int]] = Field(
        None,
        description='All restricted categories for the ads that may be shown from this snippet. Each category is represented by an integer as defined in the  ad-restricted-categories.txt.',
    )
    sensitiveCategories: Optional[List[int]] = Field(
        None,
        description='Detected sensitive categories, if any. Each category is represented by an integer as defined in  ad-sensitive-categories.txt. Read-only. This field should not be set in requests.',
    )
    servingRestrictions: Optional[List[ServingRestriction]] = Field(
        None,
        description='The granular status of this ad in specific contexts. A context here relates to where something ultimately serves (for example, a physical location, a platform, an HTTPS vs HTTP request, or the type of auction). Read-only. This field should not be set in requests. See the examples in the Creatives guide for more details.',
    )
    vendorType: Optional[List[int]] = Field(
        None,
        description='List of vendor types for the ads that may be shown from this snippet. Each vendor type is represented by an integer as defined in vendors.txt.',
    )
    version: Optional[int] = Field(
        None,
        description='The version for this creative. Read-only. This field should not be set in requests.',
    )
    videoURL: Optional[str] = Field(
        None,
        description='The URL to fetch a video ad. If set, HTMLSnippet, videoVastXML, and nativeAd should not be set. Note, this is different from resource.native_ad.video_url above.',
    )
    videoVastXML: Optional[str] = Field(
        None,
        description='The contents of a VAST document for a video ad. This document should conform to the VAST 2.0 or 3.0 standard. If set, HTMLSnippet, videoURL, and nativeAd and should not be set.',
    )
    width: Optional[int] = Field(None, description='Ad width.')


class DealStatus(BaseModel):
    arcStatus: Optional[str] = Field(None, description='ARC approval status.')
    dealId: Optional[str] = Field(None, description='External deal ID.')
    webPropertyId: Optional[int] = Field(None, description='Publisher ID.')


class CreativeDealIds(BaseModel):
    dealStatuses: Optional[List[DealStatus]] = Field(
        None, description='A list of external deal ids and ARC approval status.'
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#creativeDealIds', description='Resource type.'
    )


class CreativesList(BaseModel):
    items: Optional[List[Creative]] = Field(None, description='A list of creatives.')
    kind: Optional[str] = Field(
        'adexchangebuyer#creativesList', description='Resource type.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Continuation token used to page through creatives. To retrieve the next page of results, set the next request\'s "pageToken" value to this.',
    )


class DealServingMetadataDealPauseStatus(BaseModel):
    buyerPauseReason: Optional[str] = None
    firstPausedBy: Optional[str] = Field(
        None,
        description='If the deal is paused, records which party paused the deal first.',
    )
    hasBuyerPaused: Optional[bool] = None
    hasSellerPaused: Optional[bool] = None
    sellerPauseReason: Optional[str] = None


class DeleteOrderDealsRequest(BaseModel):
    dealIds: Optional[List[str]] = Field(
        None, description='List of deals to delete for a given proposal'
    )
    proposalRevisionNumber: Optional[str] = Field(
        None, description='The last known proposal revision number.'
    )
    updateAction: Optional[str] = Field(
        None, description='Indicates an optional action to take on the proposal'
    )


class DeliveryControlFrequencyCap(BaseModel):
    maxImpressions: Optional[int] = None
    numTimeUnits: Optional[int] = None
    timeUnitType: Optional[str] = None


class DimensionDimensionValue(BaseModel):
    id: Optional[int] = Field(None, description='Id of the dimension.')
    name: Optional[str] = Field(
        None,
        description='Name of the dimension mainly for debugging purposes, except for the case of CREATIVE_SIZE. For CREATIVE_SIZE, strings are used instead of ids.',
    )
    percentage: Optional[int] = Field(
        None,
        description="Percent of total impressions for a dimension type. e.g. {dimension_type: 'GENDER', [{dimension_value: {id: 1, name: 'MALE', percentage: 60}}]} Gender MALE is 60% of all impressions which have gender.",
    )


class MarketplaceNote(BaseModel):
    creatorRole: Optional[str] = Field(
        None,
        description='The role of the person (buyer/seller) creating the note. (readonly)',
    )
    dealId: Optional[str] = Field(
        None,
        description='Notes can optionally be associated with a deal. (readonly, except on create)',
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#marketplaceNote',
        description='Identifies what kind of resource this is. Value: the fixed string "adexchangebuyer#marketplaceNote".',
    )
    note: Optional[str] = Field(
        None, description='The actual note to attach. (readonly, except on create)'
    )
    noteId: Optional[str] = Field(
        None, description='The unique id for the note. (readonly)'
    )
    proposalId: Optional[str] = Field(
        None, description='The proposalId that a note is attached to. (readonly)'
    )
    proposalRevisionNumber: Optional[str] = Field(
        None,
        description='If the note is associated with a proposal revision number, then store that here. (readonly, except on create)',
    )
    timestampMs: Optional[str] = Field(
        None,
        description='The timestamp (ms since epoch) that this note was created. (readonly)',
    )


class MobileApplication(BaseModel):
    appStore: Optional[str] = None
    externalAppId: Optional[str] = None


class PerformanceReport(BaseModel):
    bidRate: Optional[float] = Field(
        None, description='The number of bid responses with an ad.'
    )
    bidRequestRate: Optional[float] = Field(
        None, description='The number of bid requests sent to your bidder.'
    )
    calloutStatusRate: Optional[List] = Field(
        None,
        description='Rate of various prefiltering statuses per match. Please refer to the callout-status-codes.txt file for different statuses.',
    )
    cookieMatcherStatusRate: Optional[List] = Field(
        None, description='Average QPS for cookie matcher operations.'
    )
    creativeStatusRate: Optional[List] = Field(
        None,
        description='Rate of ads with a given status. Please refer to the creative-status-codes.txt file for different statuses.',
    )
    filteredBidRate: Optional[float] = Field(
        None,
        description='The number of bid responses that were filtered due to a policy violation or other errors.',
    )
    hostedMatchStatusRate: Optional[List] = Field(
        None, description='Average QPS for hosted match operations.'
    )
    inventoryMatchRate: Optional[float] = Field(
        None,
        description='The number of potential queries based on your pretargeting settings.',
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#performanceReport', description='Resource type.'
    )
    latency50thPercentile: Optional[float] = Field(
        None,
        description='The 50th percentile round trip latency(ms) as perceived from Google servers for the duration period covered by the report.',
    )
    latency85thPercentile: Optional[float] = Field(
        None,
        description='The 85th percentile round trip latency(ms) as perceived from Google servers for the duration period covered by the report.',
    )
    latency95thPercentile: Optional[float] = Field(
        None,
        description='The 95th percentile round trip latency(ms) as perceived from Google servers for the duration period covered by the report.',
    )
    noQuotaInRegion: Optional[float] = Field(
        None, description='Rate of various quota account statuses per quota check.'
    )
    outOfQuota: Optional[float] = Field(
        None, description='Rate of various quota account statuses per quota check.'
    )
    pixelMatchRequests: Optional[float] = Field(
        None, description='Average QPS for pixel match requests from clients.'
    )
    pixelMatchResponses: Optional[float] = Field(
        None, description='Average QPS for pixel match responses from clients.'
    )
    quotaConfiguredLimit: Optional[float] = Field(
        None, description='The configured quota limits for this account.'
    )
    quotaThrottledLimit: Optional[float] = Field(
        None, description='The throttled quota limits for this account.'
    )
    region: Optional[str] = Field(
        None, description='The trading location of this data.'
    )
    successfulRequestRate: Optional[float] = Field(
        None,
        description='The number of properly formed bid responses received by our servers within the deadline.',
    )
    timestamp: Optional[str] = Field(
        None,
        description='The unix timestamp of the starting time of this performance data.',
    )
    unsuccessfulRequestRate: Optional[float] = Field(
        None,
        description='The number of bid responses that were unsuccessful due to timeouts, incorrect formatting, etc.',
    )


class PerformanceReportList(BaseModel):
    kind: Optional[str] = Field(
        'adexchangebuyer#performanceReportList', description='Resource type.'
    )
    performanceReport: Optional[List[PerformanceReport]] = Field(
        None, description='A list of performance reports relevant for the account.'
    )


class Dimension1(BaseModel):
    height: Optional[str] = Field(None, description='Height in pixels.')
    width: Optional[str] = Field(None, description='Width in pixels.')


class ExcludedPlacement(BaseModel):
    token: Optional[str] = Field(
        None,
        description='The value of the placement. Interpretation depends on the placement type, e.g. URL for a site placement, channel name for a channel placement, app id for a mobile app placement.',
    )
    type: Optional[str] = Field(None, description='The type of the placement.')


class Placement(BaseModel):
    token: Optional[str] = Field(
        None,
        description='The value of the placement. Interpretation depends on the placement type, e.g. URL for a site placement, channel name for a channel placement, app id for a mobile app placement.',
    )
    type: Optional[str] = Field(None, description='The type of the placement.')


class VideoPlayerSize(BaseModel):
    aspectRatio: Optional[str] = Field(
        None,
        description='The type of aspect ratio. Leave this field blank to match all aspect ratios.',
    )
    minHeight: Optional[str] = Field(
        None,
        description='The minimum player height in pixels. Leave this field blank to match any player height.',
    )
    minWidth: Optional[str] = Field(
        None,
        description='The minimum player width in pixels. Leave this field blank to match any player width.',
    )


class PretargetingConfig(BaseModel):
    billingId: Optional[str] = Field(
        None,
        description='The id for billing purposes, provided for reference. Leave this field blank for insert requests; the id will be generated automatically.',
    )
    configId: Optional[str] = Field(
        None,
        description='The config id; generated automatically. Leave this field blank for insert requests.',
    )
    configName: Optional[str] = Field(
        None,
        description='The name of the config. Must be unique. Required for all requests.',
    )
    creativeType: Optional[List[str]] = Field(
        None,
        description='List must contain exactly one of PRETARGETING_CREATIVE_TYPE_HTML or PRETARGETING_CREATIVE_TYPE_VIDEO.',
    )
    dimensions: Optional[List[Dimension1]] = Field(
        None,
        description='Requests which allow one of these (width, height) pairs will match. All pairs must be supported ad dimensions.',
    )
    excludedContentLabels: Optional[List[str]] = Field(
        None,
        description='Requests with any of these content labels will not match. Values are from content-labels.txt in the downloadable files section.',
    )
    excludedGeoCriteriaIds: Optional[List[str]] = Field(
        None,
        description='Requests containing any of these geo criteria ids will not match.',
    )
    excludedPlacements: Optional[List[ExcludedPlacement]] = Field(
        None, description='Requests containing any of these placements will not match.'
    )
    excludedUserLists: Optional[List[str]] = Field(
        None,
        description='Requests containing any of these users list ids will not match.',
    )
    excludedVerticals: Optional[List[str]] = Field(
        None,
        description='Requests containing any of these vertical ids will not match. Values are from the publisher-verticals.txt file in the downloadable files section.',
    )
    geoCriteriaIds: Optional[List[str]] = Field(
        None,
        description='Requests containing any of these geo criteria ids will match.',
    )
    isActive: Optional[bool] = Field(
        None, description='Whether this config is active. Required for all requests.'
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#pretargetingConfig',
        description='The kind of the resource, i.e. "adexchangebuyer#pretargetingConfig".',
    )
    languages: Optional[List[str]] = Field(
        None, description='Request containing any of these language codes will match.'
    )
    maximumQps: Optional[str] = Field(
        None,
        description='The maximum QPS allocated to this pretargeting configuration, used for pretargeting-level QPS limits. By default, this is not set, which indicates that there is no QPS limit at the configuration level (a global or account-level limit may still be imposed).',
    )
    minimumViewabilityDecile: Optional[int] = Field(
        None,
        description='Requests where the predicted viewability is below the specified decile will not match. E.g. if the buyer sets this value to 5, requests from slots where the predicted viewability is below 50% will not match. If the predicted viewability is unknown this field will be ignored.',
    )
    mobileCarriers: Optional[List[str]] = Field(
        None,
        description='Requests containing any of these mobile carrier ids will match. Values are from mobile-carriers.csv in the downloadable files section.',
    )
    mobileDevices: Optional[List[str]] = Field(
        None,
        description='Requests containing any of these mobile device ids will match. Values are from mobile-devices.csv in the downloadable files section.',
    )
    mobileOperatingSystemVersions: Optional[List[str]] = Field(
        None,
        description='Requests containing any of these mobile operating system version ids will match. Values are from mobile-os.csv in the downloadable files section.',
    )
    placements: Optional[List[Placement]] = Field(
        None, description='Requests containing any of these placements will match.'
    )
    platforms: Optional[List[str]] = Field(
        None,
        description='Requests matching any of these platforms will match. Possible values are PRETARGETING_PLATFORM_MOBILE, PRETARGETING_PLATFORM_DESKTOP, and PRETARGETING_PLATFORM_TABLET.',
    )
    supportedCreativeAttributes: Optional[List[str]] = Field(
        None,
        description='Creative attributes should be declared here if all creatives corresponding to this pretargeting configuration have that creative attribute. Values are from pretargetable-creative-attributes.txt in the downloadable files section.',
    )
    userIdentifierDataRequired: Optional[List[str]] = Field(
        None,
        description="Requests containing the specified type of user data will match. Possible values are HOSTED_MATCH_DATA, which means the request is cookie-targetable and has a match in the buyer's hosted match table, and COOKIE_OR_IDFA, which means the request has either a targetable cookie or an iOS IDFA.",
    )
    userLists: Optional[List[str]] = Field(
        None, description='Requests containing any of these user list ids will match.'
    )
    vendorTypes: Optional[List[str]] = Field(
        None,
        description='Requests that allow any of these vendor ids will match. Values are from vendors.txt in the downloadable files section.',
    )
    verticals: Optional[List[str]] = Field(
        None, description='Requests containing any of these vertical ids will match.'
    )
    videoPlayerSizes: Optional[List[VideoPlayerSize]] = Field(
        None,
        description='Video requests satisfying any of these player size constraints will match.',
    )


class PretargetingConfigList(BaseModel):
    items: Optional[List[PretargetingConfig]] = Field(
        None, description='A list of pretargeting configs'
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#pretargetingConfigList', description='Resource type.'
    )


class Price(BaseModel):
    amountMicros: Optional[float] = Field(
        None, description='The price value in micros.'
    )
    currencyCode: Optional[str] = Field(
        None, description='The currency code for the price.'
    )
    expectedCpmMicros: Optional[float] = Field(
        None, description='In case of CPD deals, the expected CPM in micros.'
    )
    pricingType: Optional[str] = Field(
        None, description='The pricing type for the deal/product.'
    )


class PricePerBuyer(BaseModel):
    auctionTier: Optional[str] = Field(
        None, description='Optional access type for this buyer.'
    )
    billedBuyer: Optional[Buyer] = Field(
        None, description='Reference to the buyer that will get billed.'
    )
    buyer: Optional[Buyer] = Field(
        None,
        description="The buyer who will pay this price. If unset, all buyers can pay this price (if the advertisers match, and there's no more specific rule matching the buyer).",
    )
    price: Optional[Price] = Field(None, description='The specified price')


class PrivateData(BaseModel):
    referenceId: Optional[str] = None
    referencePayload: Optional[str] = None


class Seller(BaseModel):
    accountId: Optional[str] = Field(
        None,
        description='The unique id for the seller. The seller fills in this field. The seller account id is then available to buyer in the product.',
    )
    subAccountId: Optional[str] = Field(
        None, description='Optional sub-account id for the seller.'
    )


class TargetingValueDayPartTargetingDayPart(BaseModel):
    dayOfWeek: Optional[str] = None
    endHour: Optional[int] = None
    endMinute: Optional[int] = None
    startHour: Optional[int] = None
    startMinute: Optional[int] = None


class TargetingValueDemogAgeCriteria(BaseModel):
    demogAgeCriteriaIds: Optional[List[str]] = None


class TargetingValueDemogGenderCriteria(BaseModel):
    demogGenderCriteriaIds: Optional[List[str]] = None


class TargetingValueRequestPlatformTargeting(BaseModel):
    requestPlatforms: Optional[List[str]] = None


class TargetingValueSize(BaseModel):
    height: Optional[int] = Field(None, description='The height of the creative.')
    width: Optional[int] = Field(None, description='The width of the creative.')


class UpdatePrivateAuctionProposalRequest(BaseModel):
    externalDealId: Optional[str] = Field(
        None, description='The externalDealId of the deal to be updated.'
    )
    note: Optional[MarketplaceNote] = Field(
        None, description='Optional note to be added.'
    )
    proposalRevisionNumber: Optional[str] = Field(
        None, description='The current revision number of the proposal to be updated.'
    )
    updateAction: Optional[str] = Field(
        None, description='The proposed action on the private auction proposal.'
    )


class Alt(Enum):
    json = 'json'


class DealsStatusFilter(Enum):
    approved = 'approved'
    conditionally_approved = 'conditionally_approved'
    disapproved = 'disapproved'
    not_checked = 'not_checked'


class OpenAuctionStatusFilter(Enum):
    approved = 'approved'
    conditionally_approved = 'conditionally_approved'
    disapproved = 'disapproved'
    not_checked = 'not_checked'


class AccountId(RootModel[List[int]]):
    root: List[int]


class BuyerCreativeId(RootModel[List[str]]):
    root: List[str]


class UpdateAction(Enum):
    accept = 'accept'
    cancel = 'cancel'
    propose = 'propose'
    proposeAndAccept = 'proposeAndAccept'
    unknownAction = 'unknownAction'
    updateNonTerms = 'updateNonTerms'


class AddOrderNotesRequest(BaseModel):
    notes: Optional[List[MarketplaceNote]] = Field(
        None, description='The list of notes to add.'
    )


class AddOrderNotesResponse(BaseModel):
    notes: Optional[List[MarketplaceNote]] = None


class DealServingMetadata(BaseModel):
    alcoholAdsAllowed: Optional[bool] = Field(
        None,
        description='True if alcohol ads are allowed for this deal (read-only). This field is only populated when querying for finalized orders using the method GetFinalizedOrderDeals',
    )
    dealPauseStatus: Optional[DealServingMetadataDealPauseStatus] = Field(
        None,
        description='Tracks which parties (if any) have paused a deal. (readonly, except via PauseResumeOrderDeals action)',
    )


class DealTermsGuaranteedFixedPriceTermsBillingInfo(BaseModel):
    currencyConversionTimeMs: Optional[str] = Field(
        None,
        description="The timestamp (in ms since epoch) when the original reservation price for the deal was first converted to DFP currency. This is used to convert the contracted price into buyer's currency without discrepancy.",
    )
    dfpLineItemId: Optional[str] = Field(
        None,
        description='The DFP line item id associated with this deal. For features like CPD, buyers can retrieve the DFP line item for billing reconciliation.',
    )
    originalContractedQuantity: Optional[str] = Field(
        None,
        description='The original contracted quantity (# impressions) for this deal. To ensure delivery, sometimes the publisher will book the deal with a impression buffer, such that guaranteed_looks is greater than the contracted quantity. However clients are billed using the original contracted quantity.',
    )
    price: Optional[Price] = Field(
        None,
        description='The original reservation price for the deal, if the currency code is different from the one used in negotiation.',
    )


class DealTermsNonGuaranteedAuctionTerms(BaseModel):
    autoOptimizePrivateAuction: Optional[bool] = Field(
        None,
        description='True if open auction buyers are allowed to compete with invited buyers in this private auction (buyer-readonly).',
    )
    reservePricePerBuyers: Optional[List[PricePerBuyer]] = Field(
        None, description='Reserve price for the specified buyer.'
    )


class DealTermsNonGuaranteedFixedPriceTerms(BaseModel):
    fixedPrices: Optional[List[PricePerBuyer]] = Field(
        None, description='Fixed price for the specified buyer.'
    )


class DealTermsRubiconNonGuaranteedTerms(BaseModel):
    priorityPrice: Optional[Price] = Field(
        None, description='Optional price for Rubicon priority access in the auction.'
    )
    standardPrice: Optional[Price] = Field(
        None, description='Optional price for Rubicon standard access in the auction.'
    )


class DeliveryControl(BaseModel):
    creativeBlockingLevel: Optional[str] = None
    deliveryRateType: Optional[str] = None
    frequencyCaps: Optional[List[DeliveryControlFrequencyCap]] = None


class Dimension(BaseModel):
    dimensionType: Optional[str] = None
    dimensionValues: Optional[List[DimensionDimensionValue]] = None


class GetOrderNotesResponse(BaseModel):
    notes: Optional[List[MarketplaceNote]] = Field(
        None,
        description='The list of matching notes. The notes for a proposal are ordered from oldest to newest. If the notes span multiple proposals, they will be grouped by proposal, with the notes for the most recently modified proposal appearing first.',
    )


class MarketplaceDealParty(BaseModel):
    buyer: Optional[Buyer] = Field(
        None,
        description='The buyer/seller associated with the deal. One of buyer/seller is specified for a deal-party.',
    )
    seller: Optional[Seller] = Field(
        None,
        description='The buyer/seller associated with the deal. One of buyer/seller is specified for a deal party.',
    )


class MarketplaceLabel(BaseModel):
    accountId: Optional[str] = Field(
        None, description='The accountId of the party that created the label.'
    )
    createTimeMs: Optional[str] = Field(
        None, description='The creation time (in ms since epoch) for the label.'
    )
    deprecatedMarketplaceDealParty: Optional[MarketplaceDealParty] = Field(
        None, description='Information about the party that created the label.'
    )
    label: Optional[str] = Field(None, description='The label to use.')


class Proposal(BaseModel):
    billedBuyer: Optional[Buyer] = Field(
        None,
        description='Reference to the buyer that will get billed for this proposal. (readonly)',
    )
    buyer: Optional[Buyer] = Field(
        None,
        description='Reference to the buyer on the proposal. (readonly, except on create)',
    )
    buyerContacts: Optional[List[ContactInformation]] = Field(
        None, description='Optional contact information of the buyer. (seller-readonly)'
    )
    buyerPrivateData: Optional[PrivateData] = Field(
        None, description='Private data for buyer. (hidden from seller).'
    )
    dbmAdvertiserIds: Optional[List[str]] = Field(
        None, description='IDs of DBM advertisers permission to this proposal.'
    )
    hasBuyerSignedOff: Optional[bool] = Field(
        None,
        description='When an proposal is in an accepted state, indicates whether the buyer has signed off. Once both sides have signed off on a deal, the proposal can be finalized by the seller. (seller-readonly)',
    )
    hasSellerSignedOff: Optional[bool] = Field(
        None,
        description='When an proposal is in an accepted state, indicates whether the buyer has signed off Once both sides have signed off on a deal, the proposal can be finalized by the seller. (buyer-readonly)',
    )
    inventorySource: Optional[str] = Field(
        None,
        description='What exchange will provide this inventory (readonly, except on create).',
    )
    isRenegotiating: Optional[bool] = Field(
        None, description='True if the proposal is being renegotiated (readonly).'
    )
    isSetupComplete: Optional[bool] = Field(
        None,
        description='True, if the buyside inventory setup is complete for this proposal. (readonly, except via OrderSetupCompleted action) Deprecated in favor of deal level setup complete flag.',
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#proposal',
        description='Identifies what kind of resource this is. Value: the fixed string "adexchangebuyer#proposal".',
    )
    labels: Optional[List[MarketplaceLabel]] = Field(
        None, description='List of labels associated with the proposal. (readonly)'
    )
    lastUpdaterOrCommentorRole: Optional[str] = Field(
        None,
        description='The role of the last user that either updated the proposal or left a comment. (readonly)',
    )
    name: Optional[str] = Field(
        None, description='The name for the proposal (updatable)'
    )
    negotiationId: Optional[str] = Field(
        None,
        description='Optional negotiation id if this proposal is a preferred deal proposal.',
    )
    originatorRole: Optional[str] = Field(
        None,
        description='Indicates whether the buyer/seller created the proposal.(readonly)',
    )
    privateAuctionId: Optional[str] = Field(
        None,
        description='Optional private auction id if this proposal is a private auction proposal.',
    )
    proposalId: Optional[str] = Field(
        None, description='The unique id of the proposal. (readonly).'
    )
    proposalState: Optional[str] = Field(
        None, description='The current state of the proposal. (readonly)'
    )
    revisionNumber: Optional[str] = Field(
        None, description='The revision number for the proposal (readonly).'
    )
    revisionTimeMs: Optional[str] = Field(
        None,
        description='The time (ms since epoch) when the proposal was last revised (readonly).',
    )
    seller: Optional[Seller] = Field(
        None,
        description='Reference to the seller on the proposal. (readonly, except on create)',
    )
    sellerContacts: Optional[List[ContactInformation]] = Field(
        None, description='Optional contact information of the seller (buyer-readonly).'
    )


class PublisherProvidedForecast(BaseModel):
    dimensions: Optional[List[Dimension]] = Field(
        None, description='Publisher provided dimensions. E.g. geo, sizes etc...'
    )
    weeklyImpressions: Optional[str] = Field(
        None, description='Publisher provided weekly impressions.'
    )
    weeklyUniques: Optional[str] = Field(
        None, description='Publisher provided weekly uniques.'
    )


class TargetingValueCreativeSize(BaseModel):
    allowedFormats: Optional[List[str]] = Field(
        None, description='The formats allowed by the publisher.'
    )
    companionSizes: Optional[List[TargetingValueSize]] = Field(
        None, description='For video size type, the list of companion sizes.'
    )
    creativeSizeType: Optional[str] = Field(None, description='The Creative size type.')
    nativeTemplate: Optional[str] = Field(
        None, description='The native template for native ad.'
    )
    size: Optional[TargetingValueSize] = Field(
        None,
        description='For regular or video creative size type, specifies the size of the creative.',
    )
    skippableAdType: Optional[str] = Field(
        None, description='The skippable ad type for video size.'
    )


class TargetingValueDayPartTargeting(BaseModel):
    dayParts: Optional[List[TargetingValueDayPartTargetingDayPart]] = None
    timeZoneType: Optional[str] = None


class CreateOrdersRequest(BaseModel):
    proposals: Optional[List[Proposal]] = Field(
        None, description='The list of proposals to create.'
    )
    webPropertyCode: Optional[str] = Field(
        None, description='Web property id of the seller creating these orders'
    )


class CreateOrdersResponse(BaseModel):
    proposals: Optional[List[Proposal]] = Field(
        None, description='The list of proposals successfully created.'
    )


class DealTermsGuaranteedFixedPriceTerms(BaseModel):
    billingInfo: Optional[DealTermsGuaranteedFixedPriceTermsBillingInfo] = Field(
        None,
        description='External billing info for this Deal. This field is relevant when external billing info such as price has a different currency code than DFP/AdX.',
    )
    fixedPrices: Optional[List[PricePerBuyer]] = Field(
        None, description='Fixed price for the specified buyer.'
    )
    guaranteedImpressions: Optional[str] = Field(
        None,
        description='Guaranteed impressions as a percentage. This is the percentage of guaranteed looks that the buyer is guaranteeing to buy.',
    )
    guaranteedLooks: Optional[str] = Field(
        None,
        description='Count of guaranteed looks. Required for deal, optional for product. For CPD deals, buyer changes to guaranteed_looks will be ignored.',
    )
    minimumDailyLooks: Optional[str] = Field(
        None,
        description='Count of minimum daily looks for a CPD deal. For CPD deals, buyer should negotiate on this field instead of guaranteed_looks.',
    )


class GetOrdersResponse(BaseModel):
    proposals: Optional[List[Proposal]] = Field(
        None, description='The list of matching proposals.'
    )


class PublisherProfileApiProto(BaseModel):
    audience: Optional[str] = Field(
        None, description='Publisher provided info on its audience.'
    )
    buyerPitchStatement: Optional[str] = Field(
        None, description='A pitch statement for the buyer'
    )
    directContact: Optional[str] = Field(
        None, description='Direct contact for the publisher profile.'
    )
    exchange: Optional[str] = Field(
        None,
        description='Exchange where this publisher profile is from. E.g. AdX, Rubicon etc...',
    )
    forecastInventory: Optional[str] = None
    googlePlusLink: Optional[str] = Field(
        None, description="Link to publisher's Google+ page."
    )
    isParent: Optional[bool] = Field(
        None,
        description='True, if this is the parent profile, which represents all domains owned by the publisher.',
    )
    isPublished: Optional[bool] = Field(
        None, description='True, if this profile is published. Deprecated for state.'
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#publisherProfileApiProto',
        description='Identifies what kind of resource this is. Value: the fixed string "adexchangebuyer#publisherProfileApiProto".',
    )
    logoUrl: Optional[str] = Field(
        None, description='The url to the logo for the publisher.'
    )
    mediaKitLink: Optional[str] = Field(
        None, description='The url for additional marketing and sales materials.'
    )
    name: Optional[str] = None
    overview: Optional[str] = Field(None, description='Publisher provided overview.')
    profileId: Optional[int] = Field(
        None,
        description='The pair of (seller.account_id, profile_id) uniquely identifies a publisher profile for a given publisher.',
    )
    programmaticContact: Optional[str] = Field(
        None, description='Programmatic contact for the publisher profile.'
    )
    publisherAppIds: Optional[List[str]] = Field(
        None,
        description='The list of app IDs represented in this publisher profile. Empty if this is a parent profile. Deprecated in favor of publisher_app.',
    )
    publisherApps: Optional[List[MobileApplication]] = Field(
        None,
        description='The list of apps represented in this publisher profile. Empty if this is a parent profile.',
    )
    publisherDomains: Optional[List[str]] = Field(
        None,
        description='The list of domains represented in this publisher profile. Empty if this is a parent profile.',
    )
    publisherProfileId: Optional[str] = Field(
        None, description='Unique Id for publisher profile.'
    )
    publisherProvidedForecast: Optional[PublisherProvidedForecast] = Field(
        None, description='Publisher provided forecasting information.'
    )
    rateCardInfoLink: Optional[str] = Field(
        None, description='Link to publisher rate card'
    )
    samplePageLink: Optional[str] = Field(
        None, description='Link for a sample content page.'
    )
    seller: Optional[Seller] = Field(
        None, description='Seller of the publisher profile.'
    )
    state: Optional[str] = Field(None, description='State of the publisher profile.')
    topHeadlines: Optional[List[str]] = Field(
        None, description='Publisher provided key metrics and rankings.'
    )


class TargetingValue(BaseModel):
    creativeSizeValue: Optional[TargetingValueCreativeSize] = Field(
        None, description='The creative size value to exclude/include.'
    )
    dayPartTargetingValue: Optional[TargetingValueDayPartTargeting] = Field(
        None,
        description='The daypart targeting to include / exclude. Filled in when the key is GOOG_DAYPART_TARGETING.',
    )
    demogAgeCriteriaValue: Optional[TargetingValueDemogAgeCriteria] = None
    demogGenderCriteriaValue: Optional[TargetingValueDemogGenderCriteria] = None
    longValue: Optional[str] = Field(
        None, description='The long value to exclude/include.'
    )
    requestPlatformTargetingValue: Optional[TargetingValueRequestPlatformTargeting] = (
        None
    )
    stringValue: Optional[str] = Field(
        None, description='The string value to exclude/include.'
    )


class DealTerms(BaseModel):
    brandingType: Optional[str] = Field(
        None, description='Visibility of the URL in bid requests.'
    )
    crossListedExternalDealIdType: Optional[str] = Field(
        None,
        description='Indicates that this ExternalDealId exists under at least two different AdxInventoryDeals. Currently, the only case that the same ExternalDealId will exist is programmatic cross sell case.',
    )
    description: Optional[str] = Field(
        None, description='Description for the proposed terms of the deal.'
    )
    estimatedGrossSpend: Optional[Price] = Field(
        None,
        description='Non-binding estimate of the estimated gross spend for this deal Can be set by buyer or seller.',
    )
    estimatedImpressionsPerDay: Optional[str] = Field(
        None,
        description='Non-binding estimate of the impressions served per day Can be set by buyer or seller.',
    )
    guaranteedFixedPriceTerms: Optional[DealTermsGuaranteedFixedPriceTerms] = Field(
        None, description='The terms for guaranteed fixed price deals.'
    )
    nonGuaranteedAuctionTerms: Optional[DealTermsNonGuaranteedAuctionTerms] = Field(
        None, description='The terms for non-guaranteed auction deals.'
    )
    nonGuaranteedFixedPriceTerms: Optional[DealTermsNonGuaranteedFixedPriceTerms] = (
        Field(None, description='The terms for non-guaranteed fixed price deals.')
    )
    rubiconNonGuaranteedTerms: Optional[DealTermsRubiconNonGuaranteedTerms] = Field(
        None, description='The terms for rubicon non-guaranteed deals.'
    )
    sellerTimeZone: Optional[str] = Field(
        None,
        description='For deals with Cost Per Day billing, defines the timezone used to mark the boundaries of a day (buyer-readonly)',
    )


class GetPublisherProfilesByAccountIdResponse(BaseModel):
    profiles: Optional[List[PublisherProfileApiProto]] = Field(
        None, description='Profiles for the requested publisher'
    )


class SharedTargeting(BaseModel):
    exclusions: Optional[List[TargetingValue]] = Field(
        None,
        description="The list of values to exclude from targeting. Each value is AND'd together.",
    )
    inclusions: Optional[List[TargetingValue]] = Field(
        None,
        description="The list of value to include as part of the targeting. Each value is OR'd together.",
    )
    key: Optional[str] = Field(
        None, description='The key representing the shared targeting criterion.'
    )


class MarketplaceDeal(BaseModel):
    buyerPrivateData: Optional[PrivateData] = Field(
        None, description='Buyer private data (hidden from seller).'
    )
    creationTimeMs: Optional[str] = Field(
        None, description='The time (ms since epoch) of the deal creation. (readonly)'
    )
    creativePreApprovalPolicy: Optional[str] = Field(
        None, description='Specifies the creative pre-approval policy (buyer-readonly)'
    )
    creativeSafeFrameCompatibility: Optional[str] = Field(
        None,
        description='Specifies whether the creative is safeFrame compatible (buyer-readonly)',
    )
    dealId: Optional[str] = Field(
        None, description='A unique deal-id for the deal (readonly).'
    )
    dealServingMetadata: Optional[DealServingMetadata] = Field(
        None,
        description='Metadata about the serving status of this deal (readonly, writes via custom actions)',
    )
    deliveryControl: Optional[DeliveryControl] = Field(
        None,
        description='The set of fields around delivery control that are interesting for a buyer to see but are non-negotiable. These are set by the publisher. This message is assigned an id of 100 since some day we would want to model this as a protobuf extension.',
    )
    externalDealId: Optional[str] = Field(
        None,
        description='The external deal id assigned to this deal once the deal is finalized. This is the deal-id that shows up in serving/reporting etc. (readonly)',
    )
    flightEndTimeMs: Optional[str] = Field(
        None,
        description='Proposed flight end time of the deal (ms since epoch) This will generally be stored in a granularity of a second. (updatable)',
    )
    flightStartTimeMs: Optional[str] = Field(
        None,
        description='Proposed flight start time of the deal (ms since epoch) This will generally be stored in a granularity of a second. (updatable)',
    )
    inventoryDescription: Optional[str] = Field(
        None, description='Description for the deal terms. (buyer-readonly)'
    )
    isRfpTemplate: Optional[bool] = Field(
        None,
        description='Indicates whether the current deal is a RFP template. RFP template is created by buyer and not based on seller created products.',
    )
    isSetupComplete: Optional[bool] = Field(
        None,
        description='True, if the buyside inventory setup is complete for this deal. (readonly, except via OrderSetupCompleted action)',
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#marketplaceDeal',
        description='Identifies what kind of resource this is. Value: the fixed string "adexchangebuyer#marketplaceDeal".',
    )
    lastUpdateTimeMs: Optional[str] = Field(
        None,
        description='The time (ms since epoch) when the deal was last updated. (readonly)',
    )
    makegoodRequestedReason: Optional[str] = None
    name: Optional[str] = Field(None, description='The name of the deal. (updatable)')
    productId: Optional[str] = Field(
        None,
        description='The product-id from which this deal was created. (readonly, except on create)',
    )
    productRevisionNumber: Optional[str] = Field(
        None,
        description='The revision number of the product that the deal was created from (readonly, except on create)',
    )
    programmaticCreativeSource: Optional[str] = Field(
        None,
        description='Specifies the creative source for programmatic deals, PUBLISHER means creative is provided by seller and ADVERTISR means creative is provided by buyer. (buyer-readonly)',
    )
    proposalId: Optional[str] = None
    sellerContacts: Optional[List[ContactInformation]] = Field(
        None,
        description='Optional Seller contact information for the deal (buyer-readonly)',
    )
    sharedTargetings: Optional[List[SharedTargeting]] = Field(
        None,
        description="The shared targeting visible to buyers and sellers. Each shared targeting entity is AND'd together. (updatable)",
    )
    syndicationProduct: Optional[str] = Field(
        None,
        description='The syndication product associated with the deal. (readonly, except on create)',
    )
    terms: Optional[DealTerms] = Field(
        None, description='The negotiable terms of the deal. (updatable)'
    )
    webPropertyCode: Optional[str] = None


class Product(BaseModel):
    billedBuyer: Optional[Buyer] = Field(
        None,
        description='The billed buyer corresponding to the buyer that created the offer. (readonly, except on create)',
    )
    buyer: Optional[Buyer] = Field(
        None,
        description='The buyer that created the offer if this is a buyer initiated offer (readonly, except on create)',
    )
    creationTimeMs: Optional[str] = Field(
        None, description='Creation time in ms. since epoch (readonly)'
    )
    creatorContacts: Optional[List[ContactInformation]] = Field(
        None,
        description='Optional contact information for the creator of this product. (buyer-readonly)',
    )
    creatorRole: Optional[str] = Field(
        None,
        description='The role that created the offer. Set to BUYER for buyer initiated offers.',
    )
    deliveryControl: Optional[DeliveryControl] = Field(
        None,
        description='The set of fields around delivery control that are interesting for a buyer to see but are non-negotiable. These are set by the publisher. This message is assigned an id of 100 since some day we would want to model this as a protobuf extension.',
    )
    flightEndTimeMs: Optional[str] = Field(
        None,
        description='The proposed end time for the deal (ms since epoch) (buyer-readonly)',
    )
    flightStartTimeMs: Optional[str] = Field(
        None,
        description='Inventory availability dates. (times are in ms since epoch) The granularity is generally in the order of seconds. (buyer-readonly)',
    )
    hasCreatorSignedOff: Optional[bool] = Field(
        None,
        description='If the creator has already signed off on the product, then the buyer can finalize the deal by accepting the product as is. When copying to a proposal, if any of the terms are changed, then auto_finalize is automatically set to false.',
    )
    inventorySource: Optional[str] = Field(
        None,
        description='What exchange will provide this inventory (readonly, except on create).',
    )
    kind: Optional[str] = Field(
        'adexchangebuyer#product',
        description='Identifies what kind of resource this is. Value: the fixed string "adexchangebuyer#product".',
    )
    labels: Optional[List[MarketplaceLabel]] = Field(
        None,
        description='Optional List of labels for the product (optional, buyer-readonly).',
    )
    lastUpdateTimeMs: Optional[str] = Field(
        None, description='Time of last update in ms. since epoch (readonly)'
    )
    legacyOfferId: Optional[str] = Field(
        None,
        description='Optional legacy offer id if this offer is a preferred deal offer.',
    )
    marketplacePublisherProfileId: Optional[str] = Field(
        None,
        description='Marketplace publisher profile Id. This Id differs from the regular publisher_profile_id in that 1. This is a new id, the old Id will be deprecated in 2017. 2. This id uniquely identifies a publisher profile by itself.',
    )
    name: Optional[str] = Field(
        None,
        description='The name for this product as set by the seller. (buyer-readonly)',
    )
    privateAuctionId: Optional[str] = Field(
        None,
        description='Optional private auction id if this offer is a private auction offer.',
    )
    productId: Optional[str] = Field(
        None, description='The unique id for the product (readonly)'
    )
    publisherProfileId: Optional[str] = Field(
        None,
        description='Id of the publisher profile for a given seller. A (seller.account_id, publisher_profile_id) pair uniquely identifies a publisher profile. Buyers can call the PublisherProfiles::List endpoint to get a list of publisher profiles for a given seller.',
    )
    publisherProvidedForecast: Optional[PublisherProvidedForecast] = Field(
        None, description='Publisher self-provided forecast information.'
    )
    revisionNumber: Optional[str] = Field(
        None, description='The revision number of the product. (readonly)'
    )
    seller: Optional[Seller] = Field(
        None,
        description='Information about the seller that created this product (readonly, except on create)',
    )
    sharedTargetings: Optional[List[SharedTargeting]] = Field(
        None,
        description='Targeting that is shared between the buyer and the seller. Each targeting criteria has a specified key and for each key there is a list of inclusion value or exclusion values. (buyer-readonly)',
    )
    state: Optional[str] = Field(
        None, description='The state of the product. (buyer-readonly)'
    )
    syndicationProduct: Optional[str] = Field(
        None,
        description='The syndication product associated with the deal. (readonly, except on create)',
    )
    terms: Optional[DealTerms] = Field(
        None, description='The negotiable terms of the deal (buyer-readonly)'
    )
    webPropertyCode: Optional[str] = Field(
        None,
        description='The web property code for the seller. This field is meant to be copied over as is when creating deals.',
    )


class AddOrderDealsRequest(BaseModel):
    deals: Optional[List[MarketplaceDeal]] = Field(
        None, description='The list of deals to add'
    )
    proposalRevisionNumber: Optional[str] = Field(
        None, description='The last known proposal revision number.'
    )
    updateAction: Optional[str] = Field(
        None, description='Indicates an optional action to take on the proposal'
    )


class AddOrderDealsResponse(BaseModel):
    deals: Optional[List[MarketplaceDeal]] = Field(
        None,
        description='List of deals added (in the same proposal as passed in the request)',
    )
    proposalRevisionNumber: Optional[str] = Field(
        None, description='The updated revision number for the proposal.'
    )


class DeleteOrderDealsResponse(BaseModel):
    deals: Optional[List[MarketplaceDeal]] = Field(
        None,
        description='List of deals deleted (in the same proposal as passed in the request)',
    )
    proposalRevisionNumber: Optional[str] = Field(
        None, description='The updated revision number for the proposal.'
    )


class EditAllOrderDealsRequest(BaseModel):
    deals: Optional[List[MarketplaceDeal]] = Field(
        None,
        description='List of deals to edit. Service may perform 3 different operations based on comparison of deals in this list vs deals already persisted in database: 1. Add new deal to proposal If a deal in this list does not exist in the proposal, the service will create a new deal and add it to the proposal. Validation will follow AddOrderDealsRequest. 2. Update existing deal in the proposal If a deal in this list already exist in the proposal, the service will update that existing deal to this new deal in the request. Validation will follow UpdateOrderDealsRequest. 3. Delete deals from the proposal (just need the id) If a existing deal in the proposal is not present in this list, the service will delete that deal from the proposal. Validation will follow DeleteOrderDealsRequest.',
    )
    proposal: Optional[Proposal] = Field(
        None,
        description='If specified, also updates the proposal in the batch transaction. This is useful when the proposal and the deals need to be updated in one transaction.',
    )
    proposalRevisionNumber: Optional[str] = Field(
        None, description='The last known revision number for the proposal.'
    )
    updateAction: Optional[str] = Field(
        None, description='Indicates an optional action to take on the proposal'
    )


class EditAllOrderDealsResponse(BaseModel):
    deals: Optional[List[MarketplaceDeal]] = Field(
        None, description='List of all deals in the proposal after edit.'
    )
    orderRevisionNumber: Optional[str] = Field(
        None,
        description='The latest revision number after the update has been applied.',
    )


class GetOffersResponse(BaseModel):
    products: Optional[List[Product]] = Field(
        None, description='The returned list of products.'
    )


class GetOrderDealsResponse(BaseModel):
    deals: Optional[List[MarketplaceDeal]] = Field(
        None, description='List of deals for the proposal'
    )
